import {
  Exercise,
  WorkoutDayPlan,
  UserProfile,
  FoodItem,
  BodyEntry,
  StepEntry,
  NutritionEntry,
  SleepEntry,
  RecoveryEntry,
  PersonalRecord,
  WorkoutSession,
} from "@/types";

export const initialUserProfile: UserProfile = {
  name: "Hussain",
  age: 22,
  heightCm: 167,
  startingWeightKg: 82.0,
  targetWeightKg: 70.0,
  currentWeightKg: 79.8,
  primaryGoal: "Fat loss + muscle retention + improved body shape",
  trainingDaysPerWeek: 5,
  restDays: ["Saturday", "Sunday"],
  gymTime: "Morning",
  stepTarget: 10000,
  calorieTarget: 1850,
  proteinTargetMin: 125,
  proteinTargetMax: 140,
  waterTargetLiters: 3.0,
  sleepTargetHours: 7.5,
  weightUnit: "kg",
  lengthUnit: "cm",
  theme: "athletic-obsidian",
};

export const allExercises: Exercise[] = [
  // PUSH / CHEST
  {
    id: "bench_press",
    name: "Barbell Bench Press",
    category: "Chest",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "front_delts"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    defaultSets: 3,
    repRange: "6–10",
    restSeconds: 150,
    tempo: "3-0-1-0",
    instructions: [
      "Lie flat on the bench with eyes directly underneath the racked barbell.",
      "Retract and depress shoulder blades, keeping a slight natural arch in the lower back.",
      "Grip the bar slightly wider than shoulder width with feet planted firmly on the floor.",
      "Unrack the bar and lower it under control to the lower-to-mid chest line over 3 seconds.",
      "Press explosively through the palms to the starting position without unlocking the shoulder blades.",
    ],
    formCues: [
      "Tuck elbows at roughly 45-60 degrees to protect shoulders",
      "Drive through the floor with your heels (leg drive)",
      "Keep wrists stacked directly over forearms",
    ],
    commonMistakes: [
      "Bouncing the bar off the ribcage",
      "Flaring elbows straight out to 90 degrees",
      "Lifting hips off the bench during the press",
    ],
    safetyNotes: [
      "Always use safety pins or spotters for heavy working sets",
      "Keep a secure thumbs-around grip (avoid suicide grip)",
    ],
  },
  {
    id: "incline_db_press",
    name: "Incline Dumbbell Press",
    category: "Chest",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    defaultSets: 3,
    repRange: "8–12",
    restSeconds: 120,
    tempo: "3-0-1-0",
    instructions: [
      "Set an adjustable bench to a 30-degree incline angle.",
      "Sit back with dumbbells resting on thighs, then kick them up to shoulder level.",
      "Retract scapulae and press the dumbbells up over the upper chest.",
      "Lower the dumbbells smoothly until you feel a deep stretch in the upper pectorals.",
      "Press back up along a slight inward arc without clinking the weights at the top.",
    ],
    formCues: ["Keep bench at 30° to target clavicular upper chest, not front delts", "Maintain full wrist control"],
    commonMistakes: ["Setting the incline too steep (45°+ shifts load to deltoids)", "Cutting depth short at the bottom"],
    safetyNotes: ["Lower dumbbells safely to thighs before sitting up at set end"],
  },
  {
    id: "machine_chest_press",
    name: "Machine Chest Press",
    category: "Chest",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "front_delts"],
    equipment: "Machine",
    difficulty: "Beginner",
    defaultSets: 2,
    repRange: "10–12",
    restSeconds: 90,
    tempo: "2-1-1-0",
    instructions: [
      "Adjust the seat height so the handles align with your mid-chest line.",
      "Keep back firmly against the pad and squeeze shoulder blades back.",
      "Press the handles smoothly forward until arms are extended without locking elbows.",
      "Return slowly to feel the chest stretch before starting the next rep.",
    ],
    formCues: ["Keep shoulders pinned to backrest throughout", "Squeeze chest at peak contraction"],
    commonMistakes: ["Rounding shoulders forward at the top", "Letting the weight stack slam on the eccentric"],
    safetyNotes: ["Use the foot assist lever to get handles into start position safely"],
  },
  {
    id: "cable_fly",
    name: "Cable Chest Fly",
    category: "Chest",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts"],
    equipment: "Cable",
    difficulty: "Beginner",
    defaultSets: 2,
    repRange: "12–15",
    restSeconds: 90,
    tempo: "3-1-1-0",
    instructions: [
      "Position pulleys around chest or shoulder height and grasp single handles.",
      "Take one step forward in a staggered stance with a slight forward torso lean.",
      "With a slight soft bend in the elbows, bring handles together in an hugging arc.",
      "Hold the peak contraction for 1 second, then control the stretch over 3 seconds.",
    ],
    formCues: ["Imagine hugging a large tree barrel", "Maintain constant slight elbow bend"],
    commonMistakes: ["Turning the fly into a press by excessively bending elbows", "Using body momentum to swing"],
    safetyNotes: ["Step back carefully when releasing cables to avoid shoulder strain"],
  },
  {
    id: "lateral_raise",
    name: "Dumbbell Lateral Raise",
    category: "Shoulders",
    primaryMuscle: "side_delts",
    secondaryMuscles: ["traps"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    defaultSets: 4,
    repRange: "12–15",
    restSeconds: 60,
    tempo: "2-0-1-1",
    instructions: [
      "Stand tall with feet shoulder-width apart, holding light dumbbells at your sides.",
      "Hinge slightly forward at hips (10 degrees) to align lateral delt with the plane of motion.",
      "Raise arms outward in the scapular plane (slightly in front of the body) until parallel with floor.",
      "Lead with elbows, hold peak for a split second, and lower with complete control.",
    ],
    formCues: ["Pour water sensation at peak (thumbs slightly lower than pinkies)", "Raise in the scapular plane 30° forward"],
    commonMistakes: ["Using heavy weights and swinging hips", "Shrugging traps up toward ears"],
    safetyNotes: ["Do not raise above shoulder height to avoid impingement"],
  },
  {
    id: "shoulder_press",
    name: "Seated Dumbbell Shoulder Press",
    category: "Shoulders",
    primaryMuscle: "front_delts",
    secondaryMuscles: ["side_delts", "triceps", "traps"],
    equipment: "Dumbbell",
    difficulty: "Intermediate",
    defaultSets: 2,
    repRange: "8–12",
    restSeconds: 120,
    tempo: "3-0-1-0",
    instructions: [
      "Set upright bench to ~75-80 degrees (not pure 90 to prevent impingement).",
      "Bring dumbbells to shoulder level with palms facing semi-pronated or forward.",
      "Press the weights vertically overhead until arms are nearly straight.",
      "Lower under control back to ear level.",
    ],
    formCues: ["Keep core braced and ribcage down", "Maintain elbow angle slightly in front of shoulders"],
    commonMistakes: ["Excessive arching of lower back", "Banging dumbbells at the top"],
    safetyNotes: ["Use knee kick to safely position heavy dumbbells"],
  },
  {
    id: "triceps_pushdown",
    name: "Cable Triceps Pushdown",
    category: "Arms",
    primaryMuscle: "triceps",
    secondaryMuscles: ["forearms"],
    equipment: "Cable",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "10–15",
    restSeconds: 90,
    tempo: "3-0-1-1",
    instructions: [
      "Attach a rope or straight bar to a high cable pulley.",
      "Keep elbows glued to the sides of your ribcage with slight torso hinge.",
      "Extend forearms downward, spreading the rope apart at full extension.",
      "Squeeze triceps hard for 1 second, then slowly allow elbows to flex up to 90 degrees.",
    ],
    formCues: ["Pin elbows as a fixed hinge pivot", "Spread the rope at bottom for peak lateral head activation"],
    commonMistakes: ["Letting elbows drift forward and backward", "Using bodyweight to lean down"],
    safetyNotes: ["Avoid hyper-extending the elbow joint forcefully"],
  },
  {
    id: "overhead_triceps_ext",
    name: "Overhead Cable Triceps Extension",
    category: "Arms",
    primaryMuscle: "triceps",
    secondaryMuscles: ["forearms"],
    equipment: "Cable",
    difficulty: "Beginner",
    defaultSets: 2,
    repRange: "10–15",
    restSeconds: 90,
    tempo: "3-0-1-0",
    instructions: [
      "Set cable at shoulder-to-chest height with rope attachment.",
      "Face away from the machine in a staggered split stance, extending arms overhead.",
      "Keep upper arms stationary next to ears as you bend elbows backward to get a full long-head stretch.",
      "Extend forearms forward and overhead, locking out with tension on the triceps.",
    ],
    formCues: ["Feel the deep stretch in the long head of the triceps behind the head", "Keep elbows stable"],
    commonMistakes: ["Flaring elbows excessively wide", "Arching lower back under load"],
    safetyNotes: ["Maintain strong core brace in split stance"],
  },

  // PULL / BACK
  {
    id: "lat_pulldown",
    name: "Wide Grip Lat Pulldown",
    category: "Back",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rear_delts", "upper_back"],
    equipment: "Cable",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "8–12",
    restSeconds: 120,
    tempo: "3-1-1-0",
    instructions: [
      "Adjust thigh pad snugly. Grip the bar just outside shoulder width with overhand grip.",
      "Sit upright with slight 10-15 degree lean back and chest high.",
      "Initiate the pull by driving shoulder blades down and pulling elbows down toward hip pockets.",
      "Touch the bar to upper chest, pause for 1 second, then control the bar back up to full stretch.",
    ],
    formCues: ["Drive elbows to back pockets", "Pull with back rather than biceps"],
    commonMistakes: ["Leaning back excessively to turn it into a row", "Yanking bar down behind neck"],
    safetyNotes: ["Do not pull behind the neck to protect cervical spine and rotator cuffs"],
  },
  {
    id: "chest_supported_row",
    name: "Chest Supported T-Bar / DB Row",
    category: "Back",
    primaryMuscle: "upper_back",
    secondaryMuscles: ["lats", "biceps", "rear_delts"],
    equipment: "Machine",
    difficulty: "Intermediate",
    defaultSets: 3,
    repRange: "8–12",
    restSeconds: 120,
    tempo: "3-1-1-0",
    instructions: [
      "Lie with chest supported against the incline pad.",
      "Grasp handles or dumbbells with neutral or overhand grip, arms fully extended.",
      "Row the weights by driving elbows back and retracting rhomboids and middle traps.",
      "Hold squeeze for 1 second, then lower smoothly through a full stretch.",
    ],
    formCues: ["Keep sternum on pad to eliminate lower back cheating", "Squeeze shoulder blades together at top"],
    commonMistakes: ["Lifting chest off pad to cheat the weight", "Jerking the neck"],
    safetyNotes: ["Chest support keeps lower back 100% safe from spinal shear"],
  },
  {
    id: "seated_cable_row",
    name: "Seated Cable Row",
    category: "Back",
    primaryMuscle: "lats",
    secondaryMuscles: ["upper_back", "biceps", "rear_delts"],
    equipment: "Cable",
    difficulty: "Beginner",
    defaultSets: 2,
    repRange: "10–12",
    restSeconds: 90,
    tempo: "2-1-1-0",
    instructions: [
      "Sit on bench with knees slightly bent, feet braced on footrests.",
      "Grasp close-grip V-handle with upright neutral spine.",
      "Pull the handle into the lower abdomen by driving elbows straight back.",
      "Squeeze lats and mid-back, then return to full arm extension with slight forward stretch.",
    ],
    formCues: ["Drive elbows back close to torso", "Keep chest proud and upright"],
    commonMistakes: ["Excessive swinging back and forth like a rowing boat", "Shrugging shoulders up"],
    safetyNotes: ["Maintain neutral lower back curvature throughout"],
  },
  {
    id: "straight_arm_pulldown",
    name: "Straight Arm Lat Pulldown",
    category: "Back",
    primaryMuscle: "lats",
    secondaryMuscles: ["triceps", "abs"],
    equipment: "Cable",
    difficulty: "Beginner",
    defaultSets: 2,
    repRange: "12–15",
    restSeconds: 90,
    tempo: "3-1-1-0",
    instructions: [
      "Attach a wide bar or rope to a high pulley. Step back with a slight torso hinge.",
      "With arms almost straight and slight elbow unlock, pull the bar in an arc down to thighs.",
      "Focus entirely on lats contracting to bring the arms down.",
      "Pause for 1 second at thighs, then control the bar back up to eye level.",
    ],
    formCues: ["Feel the lats engage like pulling a lever down", "Keep elbows locked in fixed slight bend"],
    commonMistakes: ["Bending elbows into a pushdown", "Rounding back"],
    safetyNotes: ["Brace core to stabilize hips"],
  },
  {
    id: "reverse_pec_deck",
    name: "Reverse Pec Deck (Rear Delt Fly)",
    category: "Shoulders",
    primaryMuscle: "rear_delts",
    secondaryMuscles: ["traps", "upper_back"],
    equipment: "Machine",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "12–15",
    restSeconds: 90,
    tempo: "2-1-1-0",
    instructions: [
      "Sit facing the pec deck machine with chest against the pad.",
      "Adjust handles so they align with shoulder height.",
      "Grasp handles with neutral or pronated grip and slight elbow bend.",
      "Pull arms back in a wide horizontal arc until hands are level with shoulders.",
      "Squeeze rear deltoids, then control return to the start without weights touching.",
    ],
    formCues: ["Think about pushing outward with the back of the hands", "Keep traps relaxed"],
    commonMistakes: ["Using too much weight and relying on upper traps/rhomboids", "Shrugging up"],
    safetyNotes: ["Do not over-extend past shoulder plane"],
  },
  {
    id: "db_curl",
    name: "Standing Dumbbell Biceps Curl",
    category: "Arms",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "10–12",
    restSeconds: 90,
    tempo: "3-0-1-1",
    instructions: [
      "Stand with feet hip-width, holding dumbbells at sides with palms facing thighs.",
      "Curl weights while supinating (rotating) wrists so palms face up as you lift.",
      "Squeeze biceps hard at the top without letting elbows drift far forward.",
      "Lower under strict 3-second eccentric control.",
    ],
    formCues: ["Supinate hard at the top (turn pinky upward)", "Keep upper arms vertical"],
    commonMistakes: ["Swinging body to throw weights up", "Letting elbows flare outward"],
    safetyNotes: ["Avoid hyperextending lower back"],
  },
  {
    id: "hammer_curl",
    name: "Neutral Grip Hammer Curl",
    category: "Arms",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    defaultSets: 2,
    repRange: "10–15",
    restSeconds: 90,
    tempo: "3-0-1-0",
    instructions: [
      "Hold dumbbells with palms facing each other (neutral grip).",
      "Keep elbows tucked by sides and curl dumbbells up toward shoulders.",
      "Hold peak contraction for 1 second, engaging the brachialis and brachioradialis.",
      "Lower under control to full arm extension.",
    ],
    formCues: ["Maintain neutral hammer grip throughout", "Target arm thickness and forearm power"],
    commonMistakes: ["Using momentum", "Alternating too fast without eccentric tension"],
    safetyNotes: ["Keep wrists neutral without cocking backward"],
  },
  {
    id: "cable_crunch",
    name: "Kneeling Cable Crunch",
    category: "Core",
    primaryMuscle: "abs",
    secondaryMuscles: ["obliques"],
    equipment: "Cable",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "12–15",
    restSeconds: 60,
    tempo: "3-1-1-0",
    instructions: [
      "Kneel below a high cable with a rope attachment held behind the neck / near temples.",
      "Hinge hips slightly and hold hands stationary.",
      "Flex spine by curling ribcage toward pelvis, pulling with abdominal muscles.",
      "Exhale fully and hold peak contraction for 1 second, then slowly unroll spine.",
    ],
    formCues: ["Curl the spine like rolling a carpet", "Do not sit down onto calves with hips"],
    commonMistakes: ["Moving hips instead of flexing abdominal spine", "Pulling with arms"],
    safetyNotes: ["Keep hands locked at head level to isolate core"],
  },
  {
    id: "hanging_knee_raise",
    name: "Hanging Knee Raise",
    category: "Core",
    primaryMuscle: "abs",
    secondaryMuscles: ["obliques", "forearms"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    defaultSets: 3,
    repRange: "10–15",
    restSeconds: 60,
    tempo: "2-1-1-0",
    instructions: [
      "Hang from a pull-up bar with overhand shoulder-width grip.",
      "Engage lats to stabilize shoulders and prevent swinging.",
      "Raise knees up toward chest, curling pelvis upward to activate lower rectus abdominis.",
      "Pause at top, then lower knees under control without swinging back.",
    ],
    formCues: ["Tilt pelvis up toward ribcage at top of motion", "Keep torso motionless between reps"],
    commonMistakes: ["Swinging legs with momentum", "Only lifting thighs without pelvic tilt"],
    safetyNotes: ["Use ab straps if grip fatigues before abdominal failure"],
  },

  // LEGS
  {
    id: "leg_press",
    name: "45-Degree Incline Leg Press",
    category: "Legs",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "calves"],
    equipment: "Machine",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "8–12",
    restSeconds: 150,
    tempo: "3-0-1-0",
    instructions: [
      "Sit in leg press machine with lower back and tailbone pressed firmly against seat.",
      "Place feet shoulder-width apart in middle of sled platform, toes pointing slightly out.",
      "Release safety bars and lower sled smoothly until knees are at 90 degrees.",
      "Press through full foot (midfoot and heels) to return, stopping just short of knee lockout.",
    ],
    formCues: ["Never let lower back or hips round off the seat", "Keep knees tracking in line with toes"],
    commonMistakes: ["Locking out knees violently at top", "Allowing knees to cave inward"],
    safetyNotes: ["Always keep hands on safety side handles ready to re-rack"],
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift (RDL)",
    category: "Legs",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "lower_back", "forearms"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    defaultSets: 2,
    repRange: "8–12",
    restSeconds: 150,
    tempo: "3-1-1-0",
    instructions: [
      "Stand tall holding barbell at hip level with shoulder-width overhand grip.",
      "Unlock knees slightly (keep this soft bend fixed).",
      "Push hips straight back as if closing a car door with your glutes, keeping bar skimming shins.",
      "Lower until you feel a strong hamstring stretch (around mid-shin).",
      "Drive hips forward and squeeze glutes to return to standing.",
    ],
    formCues: ["Think hip hinge (hips back), not squatting down", "Keep lats engaged and bar tight to legs"],
    commonMistakes: ["Rounding the lower back", "Bending knees too much turning into a conventional deadlift"],
    safetyNotes: ["Keep neutral cervical spine; don't crane neck up at the mirror"],
  },
  {
    id: "leg_extension",
    name: "Seated Leg Extension",
    category: "Legs",
    primaryMuscle: "quads",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "10–15",
    restSeconds: 90,
    tempo: "3-0-1-1",
    instructions: [
      "Align knee joint with machine pivot axis. Lower shin pad rests just above ankles.",
      "Grip side handles and press lower back into the pad.",
      "Extend knees smoothly to lift the weight until legs are straight.",
      "Hold peak quad contraction for 1 second, then lower under 3-second control.",
    ],
    formCues: ["Point toes slightly up", "Focus on intense teardrop quad contraction"],
    commonMistakes: ["Using momentum to kick the pad up", "Allowing hips to lift out of seat"],
    safetyNotes: ["Keep controlled tempo to protect patellar tendons"],
  },
  {
    id: "leg_curl",
    name: "Seated / Lying Hamstring Leg Curl",
    category: "Legs",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["calves"],
    equipment: "Machine",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "10–15",
    restSeconds: 90,
    tempo: "3-0-1-1",
    instructions: [
      "Adjust machine so knee aligns with pivot point and roller pad sits behind lower calves.",
      "Lock thigh pad firmly down (if seated) or keep hips flat on bench (if lying).",
      "Curl heels down/back as far as possible toward glutes.",
      "Squeeze hamstrings for 1 second, then lower slowly over 3 seconds.",
    ],
    formCues: ["Keep feet dorsiflexed (toes pulled up) to isolate hamstrings", "Full range of motion"],
    commonMistakes: ["Lifting hips off the bench", "Dropping weight with zero eccentric resistance"],
    safetyNotes: ["Do not jerk heavy loads at full extension"],
  },
  {
    id: "calf_raise",
    name: "Standing / Seated Calf Raise",
    category: "Legs",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "12–15",
    restSeconds: 60,
    tempo: "3-1-1-1",
    instructions: [
      "Position balls of feet on edge of platform with heels hanging off.",
      "Lower heels below platform level for a deep 2-3 second calf stretch.",
      "Press through the big toes to raise heels as high as possible.",
      "Hold peak contraction for 1 full second before lowering slowly.",
    ],
    formCues: ["Emphasize the deep bottom stretch and 1-second pause at the peak", "Drive through big toes"],
    commonMistakes: ["Bouncing fast at bottom Achilles tendon", "Partial range of motion"],
    safetyNotes: ["Never bounce at the bottom to avoid Achilles strain"],
  },
  {
    id: "plank",
    name: "Core Isometric Plank",
    category: "Core",
    primaryMuscle: "abs",
    secondaryMuscles: ["obliques", "glutes", "front_delts"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    defaultSets: 3,
    repRange: "30–60 sec",
    restSeconds: 60,
    tempo: "Isometric",
    instructions: [
      "Place forearms on the floor with elbows aligned directly under shoulders.",
      "Extend legs back with feet hip-width apart.",
      "Brace core as if about to be punched, squeeze glutes and quads.",
      "Maintain a straight line from crown of head to heels, breathing evenly.",
    ],
    formCues: ["Squeeze glutes and pull belly button to spine", "Do not let lower back sag"],
    commonMistakes: ["Sagging hips down", "Piking hips high in the air"],
    safetyNotes: ["Stop if lower back feels strained"],
  },
];

export const weeklyWorkoutPlan: WorkoutDayPlan[] = [
  {
    id: "mon_push",
    dayOfWeek: "Monday",
    name: "PUSH",
    focus: "Chest + Shoulders + Triceps",
    targetMuscles: ["chest", "front_delts", "side_delts", "triceps"],
    estimatedMinutes: 60,
    exercises: [
      { exerciseId: "bench_press", sets: 3, repRange: "6–10", restSeconds: 150, defaultWeightKg: 30 },
      { exerciseId: "incline_db_press", sets: 3, repRange: "8–12", restSeconds: 120, defaultWeightKg: 14 },
      { exerciseId: "machine_chest_press", sets: 2, repRange: "10–12", restSeconds: 90, defaultWeightKg: 35 },
      { exerciseId: "cable_fly", sets: 2, repRange: "12–15", restSeconds: 90, defaultWeightKg: 12.5 },
      { exerciseId: "lateral_raise", sets: 4, repRange: "12–15", restSeconds: 60, defaultWeightKg: 7.5 },
      { exerciseId: "shoulder_press", sets: 2, repRange: "8–12", restSeconds: 120, defaultWeightKg: 14 },
      { exerciseId: "triceps_pushdown", sets: 3, repRange: "10–15", restSeconds: 90, defaultWeightKg: 20 },
      { exerciseId: "overhead_triceps_ext", sets: 2, repRange: "10–15", restSeconds: 90, defaultWeightKg: 15 },
    ],
    finisher: "10 min incline treadmill walking (12% incline, 4.5 km/h)",
  },
  {
    id: "tue_pull",
    dayOfWeek: "Tuesday",
    name: "PULL",
    focus: "Back + Biceps + Core",
    targetMuscles: ["lats", "upper_back", "rear_delts", "biceps", "abs"],
    estimatedMinutes: 60,
    exercises: [
      { exerciseId: "lat_pulldown", sets: 3, repRange: "8–12", restSeconds: 120, defaultWeightKg: 45 },
      { exerciseId: "chest_supported_row", sets: 3, repRange: "8–12", restSeconds: 120, defaultWeightKg: 35 },
      { exerciseId: "seated_cable_row", sets: 2, repRange: "10–12", restSeconds: 90, defaultWeightKg: 40 },
      { exerciseId: "straight_arm_pulldown", sets: 2, repRange: "12–15", restSeconds: 90, defaultWeightKg: 17.5 },
      { exerciseId: "reverse_pec_deck", sets: 3, repRange: "12–15", restSeconds: 90, defaultWeightKg: 25 },
      { exerciseId: "db_curl", sets: 3, repRange: "10–12", restSeconds: 90, defaultWeightKg: 10 },
      { exerciseId: "hammer_curl", sets: 2, repRange: "10–15", restSeconds: 90, defaultWeightKg: 10 },
      { exerciseId: "cable_crunch", sets: 3, repRange: "12–15", restSeconds: 60, defaultWeightKg: 25 },
      { exerciseId: "hanging_knee_raise", sets: 3, repRange: "10–15", restSeconds: 60, defaultWeightKg: 0 },
    ],
    finisher: "10–15 min brisk walking",
  },
  {
    id: "wed_legs_core",
    dayOfWeek: "Wednesday",
    name: "LEGS + CORE",
    focus: "Quads + Hamstrings + Calves + Core",
    targetMuscles: ["quads", "hamstrings", "calves", "abs", "glutes"],
    estimatedMinutes: 55,
    exercises: [
      { exerciseId: "leg_press", sets: 3, repRange: "8–12", restSeconds: 150, defaultWeightKg: 110 },
      { exerciseId: "romanian_deadlift", sets: 2, repRange: "8–12", restSeconds: 150, defaultWeightKg: 50 },
      { exerciseId: "leg_extension", sets: 3, repRange: "10–15", restSeconds: 90, defaultWeightKg: 40 },
      { exerciseId: "leg_curl", sets: 3, repRange: "10–15", restSeconds: 90, defaultWeightKg: 35 },
      { exerciseId: "calf_raise", sets: 3, repRange: "12–15", restSeconds: 60, defaultWeightKg: 45 },
      { exerciseId: "cable_crunch", sets: 3, repRange: "12–15", restSeconds: 60, defaultWeightKg: 25 },
      { exerciseId: "plank", sets: 3, repRange: "30–60 sec", restSeconds: 60, defaultWeightKg: 0 },
    ],
    finisher: "No HIIT after leg day · 10 min gentle recovery stroll",
  },
  {
    id: "thu_upper",
    dayOfWeek: "Thursday",
    name: "UPPER BODY",
    focus: "Chest + Back + Shoulders + Arms",
    targetMuscles: ["chest", "lats", "upper_back", "side_delts", "rear_delts", "triceps", "biceps"],
    estimatedMinutes: 60,
    exercises: [
      { exerciseId: "incline_db_press", sets: 3, repRange: "8–12", restSeconds: 120, defaultWeightKg: 16 },
      { exerciseId: "lat_pulldown", sets: 3, repRange: "8–12", restSeconds: 120, defaultWeightKg: 47.5 },
      { exerciseId: "machine_chest_press", sets: 2, repRange: "10–12", restSeconds: 90, defaultWeightKg: 40 },
      { exerciseId: "seated_cable_row", sets: 3, repRange: "8–12", restSeconds: 120, defaultWeightKg: 42.5 },
      { exerciseId: "lateral_raise", sets: 4, repRange: "12–15", restSeconds: 60, defaultWeightKg: 8 },
      { exerciseId: "reverse_pec_deck", sets: 2, repRange: "12–15", restSeconds: 90, defaultWeightKg: 27.5 },
      { exerciseId: "triceps_pushdown", sets: 2, repRange: "10–15", restSeconds: 90, defaultWeightKg: 22.5 },
      { exerciseId: "db_curl", sets: 2, repRange: "10–15", restSeconds: 90, defaultWeightKg: 12 },
    ],
    finisher: "10–15 min incline walking",
  },
  {
    id: "fri_lower_cond",
    dayOfWeek: "Friday",
    name: "LOWER + CONDITIONING",
    focus: "Leg Hypertrophy + 3-Round HIIT Conditioning",
    targetMuscles: ["quads", "hamstrings", "calves", "glutes", "abs"],
    estimatedMinutes: 55,
    exercises: [
      { exerciseId: "leg_press", sets: 3, repRange: "8–12", restSeconds: 150, defaultWeightKg: 115 },
      { exerciseId: "leg_curl", sets: 3, repRange: "10–15", restSeconds: 90, defaultWeightKg: 37.5 },
      { exerciseId: "leg_extension", sets: 2, repRange: "10–15", restSeconds: 90, defaultWeightKg: 42.5 },
      { exerciseId: "calf_raise", sets: 3, repRange: "12–15", restSeconds: 60, defaultWeightKg: 50 },
    ],
    finisher: "Conditioning 3 Rounds: Jumping Jacks 30s | High Knees 30s | Mountain Climbers 30s | Rest 60s + 10m walking",
  },
  {
    id: "sat_rest",
    dayOfWeek: "Saturday",
    name: "REST & RECOVERY",
    focus: "Active Recovery + 10k Steps + Mobility",
    targetMuscles: [],
    estimatedMinutes: 0,
    exercises: [],
    finisher: "Light outdoor walking · Foam rolling · Hydration",
    isRestDay: true,
  },
  {
    id: "sun_rest",
    dayOfWeek: "Sunday",
    name: "REST & WEEKLY REVIEW",
    focus: "Meal Prep + Weekly Review + Sleep Target",
    targetMuscles: [],
    estimatedMinutes: 0,
    exercises: [],
    finisher: "Review week progress · Set targets for next week",
    isRestDay: true,
  },
];

export const defaultFoodLibrary: FoodItem[] = [
  { id: "f1", name: "Whole Eggs", servingSize: "3 large eggs", calories: 215, proteinG: 18, carbsG: 1.5, fatG: 15, category: "Protein" },
  { id: "f2", name: "Egg Whites", servingSize: "100g (3 whites)", calories: 52, proteinG: 11, carbsG: 0.7, fatG: 0.2, category: "Protein" },
  { id: "f3", name: "Rolled Oats", servingSize: "50g dry", calories: 190, proteinG: 7, carbsG: 34, fatG: 3.5, category: "Carb" },
  { id: "f4", name: "Skimmed Milk", servingSize: "200 ml", calories: 70, proteinG: 7, carbsG: 10, fatG: 0.4, category: "Dairy" },
  { id: "f5", name: "Banana", servingSize: "1 medium (118g)", calories: 105, proteinG: 1.3, carbsG: 27, fatG: 0.3, category: "Fruit/Veg" },
  { id: "f6", name: "Cooked White Rice", servingSize: "150g", calories: 195, proteinG: 4, carbsG: 43, fatG: 0.4, category: "Carb" },
  { id: "f7", name: "Chicken Breast (Cooked)", servingSize: "150g", calories: 245, proteinG: 46, carbsG: 0, fatG: 5.4, category: "Protein" },
  { id: "f8", name: "Soya Chunks (Dry boiled)", servingSize: "50g", calories: 172, proteinG: 26, carbsG: 16, fatG: 0.5, category: "Protein" },
  { id: "f9", name: "Low-fat Curd / Dahi", servingSize: "150g", calories: 90, proteinG: 6, carbsG: 7, fatG: 4.5, category: "Dairy" },
  { id: "f10", name: "Mixed Vegetables / Salad", servingSize: "150g", calories: 45, proteinG: 2, carbsG: 9, fatG: 0.2, category: "Fruit/Veg" },
  { id: "f11", name: "Whey Protein Isolate", servingSize: "1 scoop (30g)", calories: 120, proteinG: 25, carbsG: 1.5, fatG: 0.8, category: "Supplement" },
  { id: "f12", name: "Moong Sprouts", servingSize: "100g", calories: 105, proteinG: 7.8, carbsG: 19, fatG: 0.4, category: "Protein" },
  { id: "f13", name: "Low-fat Paneer", servingSize: "100g", calories: 180, proteinG: 18, carbsG: 3, fatG: 10, category: "Protein" },
];

export const sampleHistoricalWorkouts: WorkoutSession[] = [
  {
    id: "hist_w1_push",
    date: "2026-09-15",
    dayId: "mon_push",
    title: "Monday: PUSH (Week 1 Demo)",
    durationSeconds: 3420,
    totalVolumeKg: 7850,
    completed: true,
    isDemo: true,
    exercises: [
      {
        exerciseId: "bench_press",
        exerciseName: "Barbell Bench Press",
        sets: [
          { setNumber: 1, weightKg: 30, reps: 8, targetReps: "6–10", targetWeight: 30, completed: true, skipped: false, rpe: 8 },
          { setNumber: 2, weightKg: 30, reps: 8, targetReps: "6–10", targetWeight: 30, completed: true, skipped: false, rpe: 8.5 },
          { setNumber: 3, weightKg: 30, reps: 7, targetReps: "6–10", targetWeight: 30, completed: true, skipped: false, rpe: 9 },
        ],
      },
      {
        exerciseId: "incline_db_press",
        exerciseName: "Incline Dumbbell Press",
        sets: [
          { setNumber: 1, weightKg: 14, reps: 10, targetReps: "8–12", targetWeight: 14, completed: true, skipped: false },
          { setNumber: 2, weightKg: 14, reps: 10, targetReps: "8–12", targetWeight: 14, completed: true, skipped: false },
          { setNumber: 3, weightKg: 14, reps: 9, targetReps: "8–12", targetWeight: 14, completed: true, skipped: false },
        ],
      },
      {
        exerciseId: "lateral_raise",
        exerciseName: "Dumbbell Lateral Raise",
        sets: [
          { setNumber: 1, weightKg: 7.5, reps: 15, targetReps: "12–15", targetWeight: 7.5, completed: true, skipped: false },
          { setNumber: 2, weightKg: 7.5, reps: 14, targetReps: "12–15", targetWeight: 7.5, completed: true, skipped: false },
          { setNumber: 3, weightKg: 7.5, reps: 13, targetReps: "12–15", targetWeight: 7.5, completed: true, skipped: false },
          { setNumber: 4, weightKg: 7.5, reps: 12, targetReps: "12–15", targetWeight: 7.5, completed: true, skipped: false },
        ],
      },
    ],
  },
  {
    id: "hist_w2_push",
    date: "2026-09-22",
    dayId: "mon_push",
    title: "Monday: PUSH (Week 2 Demo)",
    durationSeconds: 3510,
    totalVolumeKg: 8240,
    completed: true,
    isDemo: true,
    exercises: [
      {
        exerciseId: "bench_press",
        exerciseName: "Barbell Bench Press",
        sets: [
          { setNumber: 1, weightKg: 30, reps: 10, targetReps: "6–10", targetWeight: 30, completed: true, skipped: false, rpe: 8.5 },
          { setNumber: 2, weightKg: 30, reps: 9, targetReps: "6–10", targetWeight: 30, completed: true, skipped: false, rpe: 9 },
          { setNumber: 3, weightKg: 30, reps: 9, targetReps: "6–10", targetWeight: 30, completed: true, skipped: false, rpe: 9.5 },
        ],
      },
      {
        exerciseId: "incline_db_press",
        exerciseName: "Incline Dumbbell Press",
        sets: [
          { setNumber: 1, weightKg: 14, reps: 12, targetReps: "8–12", targetWeight: 14, completed: true, skipped: false },
          { setNumber: 2, weightKg: 14, reps: 11, targetReps: "8–12", targetWeight: 14, completed: true, skipped: false },
          { setNumber: 3, weightKg: 14, reps: 10, targetReps: "8–12", targetWeight: 14, completed: true, skipped: false },
        ],
      },
    ],
  },
];

export const samplePersonalRecords: PersonalRecord[] = [
  { id: "pr_1", exerciseId: "bench_press", exerciseName: "Barbell Bench Press", metricType: "max_weight", value: 32.5, unit: "kg", date: "2026-09-22" },
  { id: "pr_2", exerciseId: "bench_press", exerciseName: "Barbell Bench Press", metricType: "estimated_1rm", value: 40.0, unit: "kg", date: "2026-09-22" },
  { id: "pr_3", exerciseId: "lat_pulldown", exerciseName: "Wide Grip Lat Pulldown", metricType: "max_weight", value: 50.0, unit: "kg", date: "2026-09-16" },
  { id: "pr_4", exerciseId: "leg_press", exerciseName: "45-Degree Incline Leg Press", metricType: "max_weight", value: 120.0, unit: "kg", date: "2026-09-17" },
];

export const sampleBodyEntries: BodyEntry[] = [
  { id: "b1", date: "2026-09-01", weightKg: 82.0, waistCm: 89.0, chestCm: 101.0, armsCm: 34.5, thighsCm: 60.0, hipsCm: 104.0, notes: "Starting transformation baseline" },
  { id: "b2", date: "2026-09-08", weightKg: 81.2, waistCm: 88.0, chestCm: 101.0, armsCm: 34.5, thighsCm: 59.5, hipsCm: 103.5, notes: "End of Week 1" },
  { id: "b3", date: "2026-09-15", weightKg: 80.5, waistCm: 87.2, chestCm: 101.5, armsCm: 34.8, thighsCm: 59.0, hipsCm: 102.8, notes: "End of Week 2" },
  { id: "b4", date: "2026-09-22", weightKg: 79.8, waistCm: 86.0, chestCm: 102.0, armsCm: 35.0, thighsCm: 58.5, hipsCm: 102.0, notes: "End of Week 3 · -2.2kg total down!" },
];
